name: "deploy-first-class"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy-firstclass:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying first class application"
      - run: echo "This is a placeholder for the actual deployment steps"
      - run: echo "deploy node version"
      - run: node -v
